// GENERATED by trim-code/trim.mjs -- do not edit.
// Circuit subset of USDM: bridge
import type * as __compactRuntime from '@midnight-ntwrk/compact-runtime';

export type Witnesses<PS> = {

}

export type ImpureCircuits<PS> = {
  bridge(context: __compactRuntime.CircuitContext<PS>,
         _recipient_0: Uint8Array,
         _destChain_0: bigint,
         _chainData_0: Uint8Array,
         _confirmations_0: bigint): __compactRuntime.CircuitResults<PS, bigint>;
}

export type ProvableCircuits<PS> = ImpureCircuits<PS>;
export type Circuits<PS> = ImpureCircuits<PS>;
export type PureCircuits = {
}

export type Ledger = {
  Relayers_relayers: {
    isEmpty(): boolean;
    size(): bigint;
    member(key_0: Uint8Array): boolean;
    lookup(key_0: Uint8Array): boolean;
    [Symbol.iterator](): Iterator<[Uint8Array, boolean]>
  };
  ViaIntegrationV1_messages: {
    isEmpty(): boolean;
    size(): bigint;
    member(key_0: bigint): boolean;
    lookup(key_0: bigint): { txId: bigint,
                             sender: Uint8Array,
                             recipient: Uint8Array,
                             sourceChain: bigint,
                             destChain: bigint,
                             chainData: Uint8Array,
                             confirmations: bigint
                           };
    [Symbol.iterator](): Iterator<[bigint, { txId: bigint,
  sender: Uint8Array,
  recipient: Uint8Array,
  sourceChain: bigint,
  destChain: bigint,
  chainData: Uint8Array,
  confirmations: bigint
}]>
  };
  ViaIntegrationV1_processedTransfers: {
    isEmpty(): boolean;
    size(): bigint;
    member(elem_0: bigint): boolean;
    [Symbol.iterator](): Iterator<bigint>
  };
  readonly ViaIntegrationV1_txIdBase: bigint;
  readonly ViaIntegrationV1_txIdCounter: bigint;
  readonly ViaAccessControl_ownerPubKey: Uint8Array;
  readonly ViaAccessControl_viaSupportPubKey: Uint8Array;
  readonly tokenColor: Uint8Array;
}

export type ContractReferenceLocations = any;

export declare const contractReferenceLocations : ContractReferenceLocations;

export declare class Contract<PS = any, W extends Witnesses<PS> = Witnesses<PS>> {
  witnesses: W;
  circuits: Circuits<PS>;
  impureCircuits: ImpureCircuits<PS>;
  provableCircuits: ProvableCircuits<PS>;
  constructor();
  // Declared because the SDK's `Contract` interface requires it. The constructor
  // circuit is not shipped in this trimmed artifact; calling this throws.
  initialState(context: __compactRuntime.ConstructorContext<PS>,
               ...args: any[]): __compactRuntime.ConstructorResult<PS>;
}

export declare function ledger(state: __compactRuntime.StateValue | __compactRuntime.ChargedState): Ledger;
export declare const pureCircuits: PureCircuits;
